FROM node:argon
MAINTAINER M. Peter <mp@tcs.de>

RUN apt-get update -qq && apt-get upgrade -y && apt-get install -y build-essential

RUN	mkdir -p /app/
WORKDIR /app/

COPY package.json /app/package.json
RUN npm install
COPY Gruntfile.coffee /app/Gruntfile.coffee

RUN npm install -g node-gyp
WORKDIR /app/node_modules/nsqjs/node_modules/snappystream/node_modules/snappy
RUN node-gyp rebuild
WORKDIR /app/

COPY _src/ /app/_src/

RUN npm run build

CMD [ "npm", "run", "test" ]
